# version: '3.9' OBSOLETO

services:
    # Base de dados Postgres
    mobidata-postgres:
        image: postgres:17-alpine
        # Pasta de persistência do banco no container docker é mobidata-db-postgres
        volumes:
            - mobidata-db-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: k1llC4r5
            POSTGRES_USER: mobidatauser
            POSTGRES_DB: postgres
        # Porta exposta no localhost do usuário é 25432
        ports:
            - "25432:5432"
        
    mobidata-app:
        container_name: mobidata_app
        # Quando você ver "build: .", isso significa que estamos importando o Dockerfile localizado na mesma pasta que o docker-compose
        build: .
        # Porta exposta do django no localhost do usuário é 28000, evitando de conflitar com a porta 8000, mas é possível configurar outras portas no lugar dela :)
        ports:
            - "28000:8000" 
        # Pasta de persistência mobidata-app é homônima ao app (não precisa ser homônimo mas estamos tentando manter as coisas aqui um pouco higiênicas)
        volumes:
            - ./mobidata2-app:/app
        command: >
            sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        environment:
            DB_HOST: mobidata-postgres
            DB_NAME: postgres
            DB_NAME_2: dados_mobilidade
            DB_USER: mobidatauser
            DB_PASSWORD: k1llC4r5
        depends_on:
            - mobidata-postgres

    pgadmin-mobidata:
        image: dpage/pgadmin4
        restart: always
        ports:
            - "25050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: acesso@mobidata2.net
            PGADMIN_DEFAULT_PASSWORD: acessoMobidata2025
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    mobidata-db-postgres:
    pgadmin-data: