# Generated by Django 5.1.6 on 2025-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoIdadeMediaFrota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('idade_media', models.FloatField()),
            ],
            options={
                'verbose_name': 'Histórico da Idade Média da Frota',
                'verbose_name_plural': 'Histórico da Idade Média da Frota',
                'db_table': 'historico_idade_media_frota',
            },
        ),
    ]
