# Generated by Django 5.1.6 on 2025-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquisicoesDeOnibusPorMes',
            fields=[
                ('id_aquisicao_mes', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('qtd_onibus', models.IntegerField(blank=True, null=True)),
                ('novo_ou_usado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aquisicoes_de_onibus_por_mes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concessionarias',
            fields=[
                ('id_concessionaria', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome_concessionaria', models.CharField(blank=True, max_length=60, null=True)),
                ('endereco_garagens', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'concessionarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorredoresDeOnibus',
            fields=[
                ('id_corredor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_corredor', models.CharField(blank=True, max_length=255, null=True)),
                ('qtd_onibus_por_hora', models.IntegerField(blank=True, null=True)),
                ('extensao_em_kms', models.FloatField(blank=True, null=True)),
                ('qtd_linhas_convencionais', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corredores_de_onibus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrotaOperante',
            fields=[
                ('id_frota_operante_mes', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('qtd_operante_de_onibus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'frota_operante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrotaTotal',
            fields=[
                ('id_frota_total_mes', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('qtd_total_de_onibus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'frota_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdadeMediaDaFrota',
            fields=[
                ('id_idade_media_mes', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('idade_media', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'idade_media_da_frota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeVeiculo',
            fields=[
                ('id_tipo_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('vida_util_em_anos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_de_veiculo',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='historicoidademediafrota',
            options={'managed': False},
        ),
    ]
