# Generated by Django 5.1.6 on 2025-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_aquisicoesdeonibuspormes_concessionarias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosStco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('passageiros_total', models.BigIntegerField(blank=True, null=True)),
                ('passageiros_equivalente', models.BigIntegerField(blank=True, null=True)),
                ('quilometragem_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('frota_operante', models.IntegerField(blank=True, null=True)),
                ('viagens', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('desempenho_operacional', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passageiros_por_viagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('passageiros_por_veiculo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kms_por_viagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'dados_stco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistribuicaoTaxisPorTipoDeServico',
            fields=[
                ('id_distribuicao_taxis_por_tipo_de_servico', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('tipo_de_servico', models.TextField(blank=True, null=True)),
                ('entidade_operadora', models.TextField(blank=True, null=True)),
                ('total_de_veiculos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distribuicao_taxis_por_tipo_de_servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrotaDeTaxis',
            fields=[
                ('id_frota_taxis', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('taxis_comum_autonomos', models.IntegerField(blank=True, null=True)),
                ('taxis_comum_empresas', models.IntegerField(blank=True, null=True)),
                ('total_taxis_comum', models.IntegerField(blank=True, null=True)),
                ('taxis_especiais', models.IntegerField(blank=True, null=True)),
                ('total_geral', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'frota_de_taxis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoPassageirosTransportados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('passageiros', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_passageiros_transportados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoPassageirosTransportadosMetroAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('passageiros', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_passageiros_transportados_metro_ano',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoPassageirosTransportadosMetroMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('passageiros', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_passageiros_transportados_metro_mes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoQuilometragemPercorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('quilometragem', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_quilometragem_percorrida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdadeMediaDaFrotaDeTaxis',
            fields=[
                ('id_idade_media_taxis', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('idade_media', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'idade_media_da_frota_de_taxis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadoresFinanceirosStco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(db_comment='Tipo de indicador financeiro (Receita Bruta, Receita Líquida, etc.)', max_length=50)),
                ('ano', models.IntegerField(db_comment='Ano de referência do dado')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unidade_medida', models.CharField(blank=True, db_comment='Unidade de medida (R$, %)', max_length=20, null=True)),
                ('fonte', models.CharField(blank=True, db_comment='Fonte dos dados', max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, db_comment='Observações adicionais sobre o registro', null=True)),
            ],
            options={
                'db_table': 'indicadores_financeiros_stco',
                'db_table_comment': 'Armazena os indicadores financeiros do Sistema de Transporte Coletivo por Ônibus (STCO)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('data_ajuste', models.DateField()),
                ('valor_salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ato_legal', models.CharField(max_length=50)),
                ('percentual_ajuste', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salario_minimo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarifaPrecoStco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_alteracao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarifa_preco_stco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxisPorCombustivel',
            fields=[
                ('id_taxis_por_combustivel', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('tipo_combustivel', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taxis_por_combustivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposVeiculosServicoTaxis',
            fields=[
                ('id_tipos_veiculos_taxis', models.AutoField(primary_key=True, serialize=False)),
                ('ano_registro', models.IntegerField(blank=True, null=True)),
                ('mes_registro', models.IntegerField(blank=True, null=True)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_veiculos_servico_taxis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeiculosNovosAdquiridosPorAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('veiculos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veiculos_novos_adquiridos_por_ano',
                'managed': False,
            },
        ),
    ]
