# Generated by Django 5.1.6 on 2026-09-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dadosstco_distribuicaotaxisportipodeservico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArCondicionadoStco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('qtd_frota_total', models.IntegerField(blank=True, null=True)),
                ('qtd_frota_com_ar_condicionado', models.IntegerField(blank=True, null=True)),
                ('pct_frota_com_ar_condicionado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'ar_condicionado_stco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComparativoFrotaStco',
            fields=[
                ('ano', models.IntegerField(primary_key=True, serialize=False)),
                ('frota_operante', models.IntegerField(blank=True, null=True)),
                ('frota_total', models.IntegerField(blank=True, null=True)),
                ('idade_media', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('percentual_operante_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'comparativo_frota_stco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandaPaxPorPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('tipo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('demanda', models.BigIntegerField(blank=True, null=True)),
                ('demanda_int_metro', models.BigIntegerField(blank=True, null=True)),
                ('demanda_int_stec', models.BigIntegerField(blank=True, null=True)),
                ('demanda_int_brt', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demanda_pax_por_pagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandaPaxStec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('pax_total', models.BigIntegerField(blank=True, null=True)),
                ('pax_equivalente', models.BigIntegerField(blank=True, null=True)),
                ('percentual_comparativo_equivalente_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'demanda_pax_stec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoLinhasRegulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('qtd_linhas', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_linhas_regulares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoLinhasStec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('qtd_linhas', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_linhas_stec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndiceAssaltosPorViagem',
            fields=[
                ('id_indice_assaltos_por_viagem', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('indice', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'indice_assaltos_por_viagem',
                'managed': False,
            },
        ),
    ]
